### ISSUE TITLE
Spelling Errors

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#119]
I realise that there are many spelling errors. For example, instead of writing 'Outstanding Bills Amount' you write 'OutStandingBillsAmount'. Please correct all similar instances.

**Comment by AAndharia** [comment]
@jmervana  - this is very bad. Shouldn't happen again.

**Comment by jmervana** [comment]
@mnarewec 
Done please verify

**Comment by mnarewec** [comment]
@jmervana  here is one more. OutStanding should be Outstanding
![image](https://cloud.githubusercontent.com/assets/10192106/7758100/56cc775c-004a-11e5-8005-18b2b161b4af.png)

**Comment by jmervana** [comment]
@mnarewec 
Done

**Comment by mnarewec** [comment]
@jmervana , Another spelling error..
![image](https://cloud.githubusercontent.com/assets/10192106/8515678/21602f7c-23eb-11e5-97a2-1e1e532c8d0d.png)

**Comment by mnarewec** [comment]
@jmervana , yet another one.
![image](https://cloud.githubusercontent.com/assets/10192106/8515692/54a2e74e-23eb-11e5-9129-8d4db1aea2a1.png)

**Comment by jmervana** [comment]
@mnarewec 
This will resolved in next release

**Comment by mnarewec** [comment]
@jmervana , the above spelling issue is not resolved and there is also another one for you.

![image](https://cloud.githubusercontent.com/assets/10192106/8764182/bcdfa900-2e09-11e5-8b01-70f3b4824f3a.png)

**Comment by jmervana** [comment]
@mnarewec , @Talmax 
This is resolved

**Comment by Talmax** [comment]
Another spelling error again. it suppose to be "Outstanding" and not "Out Standing".

![image](https://cloud.githubusercontent.com/assets/13091499/8796827/0ed326b0-2fdb-11e5-9390-d9e8b6d13c3a.png)

**Comment by jmervana** [comment]
@Talmax 
Let me clear here

spelling should be "Outstanding" every where
like Outstanding Amount, Outstanding Bill
 is it fine?

**Comment by Talmax** [comment]
Yes, it will be viewed like that, "Outstanding Amount, Outstanding Bill etc,"

**Comment by jmervana** [comment]
@Talmax 
I have changed all Out Standing / OutStanding to Outstanding in Entire Application.

**Comment by mnarewec** [comment]
Checked and its alright. Will create new issue when spelling errors are found.
