### ISSUE TITLE
Reports >> Client Reports >> File Ledger. Exporting files to PDF.

### ISSUE THREAD

**Issue by Talmax** [AAndharia/PSB#203]
The selected files on the File ledger when export to pdf, it shows the run time error.Refer to the image below.

![image](https://cloud.githubusercontent.com/assets/13091499/9456600/3e012876-4b1d-11e5-9551-8c6c2c8d2f2a.png)

**Comment by mnarewec** [comment]
What does that mean now ?? The issue still persist at our end.

**Comment by AAndharia** [comment]
@mnarewec - please review this after you apply recent release sent by Japan. This looks to be same error as idle issue and if that's resolved, this must be resolved as well...as it was fixed globally.

**Comment by AAndharia** [comment]
please clear the cache once. if still the issue persist, please re-assign to us.

**Comment by mnarewec** [comment]
I clear cache as advise and also restart IIS but still the issue persist.

**Comment by AAndharia** [comment]
We are unable to re-produce this at all. Can you please suggest the steps to re-produce this?

**Comment by mnarewec** [comment]
Clicking on Export Button. That's all we did and it came up with errors.

**Comment by mnarewec** [comment]
This has been resolved.
